/* DO NOT EDIT!  The following declaration and its initializer are
 * generated from the original HTML file by the script, help.py.
 */

static char* HelpString =
  "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"
  "<html>\n"
  "<head>\n"
  "  <meta content=\"text/html; charset=UTF-8\" http-equiv=\"content-type\">\n"
  "  <title>Morse Help</title>\n"
  "</head>\n"
  "<body bgcolor=white>\n"
  "\n"
  "<h1>Morse Code</h1>\n"
  "\n"
  "<P>This program teaches you to receive Morse code. It starts with a\n"
  "few letters and adds more when it sees that you are ready.\n"
  "The program won't teach you to send code\n"
  "except that sending is easy to learn on your own once you know how\n"
  "the letters sound.\n"
  "\n"
  "<h1>Getting Started</h1>\n"
  "\n"
  "<p>Set the <b>Speed</b> fast enough that letters sound like a single sound,\n"
  "not a sequence of dots and dashes. Adjust the <b>Tone</b> to a pitch\n"
  "that you find pleasing.\n"
  "\n"
  "<p>Click in the text field to start the program sending. It will send one\n"
  "letter and then wait for you to type it. It ignores wrong answers and\n"
  "does not penalize you for guessing. If you don't type the right letter\n"
  "the program will eventually show you the letter and send\n"
  "it again. Let it do this a few times to learn a new letter. Press\n"
  "the <B>Enter</B> key to pause, and again to resume.\n"
  "\n"
  "<p>The program shows in black the letters it has chosen for your practice.\n"
  "Letters it is saving show in gray. The length of the blue bars indicate\n"
  "how much emphasis the program gives each letter.\n"
  "\n"
  "<H1>Learn Quickly</H1>\n"
  "\n"
  "<p>You will enjoy learning the code more if you do it quickly. You will need\n"
  "determination that lasts for a week or two. These tips will help you learn faster.\n"
  "\n"
  "<ul>\n"
  "<LI>Spend at least an hour in every practice session. Let the program start\n"
  "from scratch each time. Show it what you still know. </LI>\n"
  "\n"
  "<LI>Rest for at least 15 minutes in peace and quiet when you are done.\n"
  "Your mind has to consolidate what you've learned. Other activity will interfere.\n"
  "</LI>\n"
  "\n"
  "<LI>Use the program at least once a week but no more than once a day. My\n"
  "wife learned the code in four sessions in as many days. </LI>\n"
  "\n"
  "<LI>The program sends characters quickly but with all the\n"
  "space between letters you need. Expect to average at about 5 words per minute. That is good\n"
  "enough for all ham licenses. Use tapes or on-the-air practice if you want go faster. </LI>\n"
  "</ul>\n"
  "\n"
  "\n"
  "<h1>Share the Program</h1>\n"
  "\n"
  "<p>You will find versions of this program for this and other operating systems\n"
  "at the source distribution site:\n"
  "\n"
  "<ul>\n"
  "<li>http://c2.com/morse\n"
  "</ul>\n"
  "\n"
  "This program is licensed under the terms of the GNU General Public License (GPL) Version 2.\n"
  "This means you can distribute copies freely. It also means that the source code for\n"
  "the program is available for you to use and modify but places some restrictions on\n"
  "how you distribute modified versions.\n"
  "\n"
  "</body>\n"
  "</html>\n"
;
